# Generated by Django 4.2.6 on 2023-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_softwarestate_software_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwarestate',
            options={'verbose_name': 'software state', 'verbose_name_plural': 'software states'},
        ),
        migrations.RemoveField(
            model_name='softwarestate',
            name='software updates',
        ),
        migrations.AddField(
            model_name='softwarestate',
            name='code_update',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='softwarestate',
            name='software update',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='softwarestate',
            name='version',
            field=models.CharField(default='', verbose_name='version number'),
        ),
    ]
