# Generated by Django 4.2.6 on 2023-12-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_alter_softwarestate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwarestate',
            old_name='version',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='softwarestate',
            name='code_update',
        ),
        migrations.RemoveField(
            model_name='softwarestate',
            name='software update',
        ),
    ]
