# Generated by Django 4.2.6 on 2023-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_rename_version_softwarestate_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarestate',
            name='state',
            field=models.CharField(default='', verbose_name='software state'),
        ),
    ]
