# Generated by Django 4.2.6 on 2023-12-07 15:20

from django.db import migrations
import django_yaml_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0005_alter_softwarestate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarestate',
            name='state_2',
            field=django_yaml_field.fields.YAMLField(default='', null=True, verbose_name='software state_2'),
        ),
    ]
