# Generated by Django 4.2.6 on 2023-12-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0006_softwarestate_state_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarestate',
            name='state',
            field=models.CharField(default='', null=True, verbose_name='software state'),
        ),
    ]
