# Generated by Django 4.2.6 on 2023-12-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("states", "0005_alter_softwarestate_state")
    ]

    operations = [
       
        migrations.AlterField(
            model_name='softwarestate',
            name='state',
            field=models.TextField(default='', null=True, verbose_name='software state'),
        ),
    ]
