# Generated by Django 4.2.6 on 2023-12-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0008_remove_softwarestate_state_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarestate',
            name='name',
            field=models.CharField(default='gib me name plz'),
        ),
    ]
