# Generated by Django 4.2.6 on 2023-12-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0004_device_last_online_device_ping'),
        ('states', '0009_softwarestate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='minions.device')),
                ('softwarestate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='states.softwarestate')),
            ],
        ),
    ]
