version: '3'

services:
  web:
    build: .
    volumes:
      - /home/martinmortensen/Documents/AAU/7. Semester/Project/backend_code/webapp:/app/data
      - .:/code:default

    ports:
      - "8000:8000"
    
    command: >
         sh -c "python manage.py makemigrations states --no-input &&
         python manage.py makemigrations minions --no-input &&
         python manage.py migrate &&
         uwsgi --ini ./uwsgi.ini"

    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres
    volumes:
      - /home/martinmortensen/Documents/webapp/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
volumes:
  postgres_data:

      
