version: '3'

services:
  djangoweb:
    build: .
    volumes:
      - /home/martinmortensen/Documents/AAU/7. Semester/Project/backend_code/webapp:/app/data
      - .:/code:default

    ports:
      - "8000:8000"
    
    command: >
         sh -c "python manage.py makemigrations states --no-input &&
         python manage.py makemigrations minions --no-input &&
         python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres
    volumes:
      - /home/martinmortensen/Documents/webapp/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  ftpd-server:
    container_name: ftpd-server
    image: stilliard/pure-ftpd:hardened
    ports:
      - 21:21
      - 20:20
      - 30000-30009:30000-30009
    volumes:
      - './ftp/data:/home/username/'
      - './ftp/pass:/etc/pure-ftpd/passwd'
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: "user"
      FTP_USER_PASS: "pass"
      FTP_USER_HOME: "/home/username"
    restart: always

volumes:
  postgres_data:

      
