# Generated by Django 4.2.6 on 2023-10-31 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('software_version', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
            },
        ),
        migrations.CreateModel(
            name='UpdateLogs',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('update log', models.CharField()),
            ],
        ),
    ]
