# Generated by Django 4.2.6 on 2023-10-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_addr',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
