# Generated by Django 4.2.6 on 2023-10-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0002_device_ip_addr_device_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatelogs',
            options={'verbose_name': 'updatelog', 'verbose_name_plural': 'updatelogs'},
        ),
    ]
