# Generated by Django 4.2.6 on 2023-10-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0002_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLogs',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('update log', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
