# Generated by Django 4.2.6 on 2023-11-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0003_alter_updatelogs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_online',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ping',
            field=models.IntegerField(null=True),
        ),
    ]
