# Generated by Django 4.2.6 on 2023-12-12 09:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0004_device_last_online_device_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelogs',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='minions.device'),
        ),
        migrations.AddField(
            model_name='updatelogs',
            name='name',
            field=models.CharField(default='gib name plzz'),
        ),
        migrations.AlterField(
            model_name='updatelogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13d30cc5-fd77-411e-afca-35ad3e955fba'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='updatelogs',
            name='update log',
            field=models.CharField(default='/home/user/logs'),
        ),
    ]
