# Generated by Django 4.2.6 on 2023-12-13 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0005_updatelogs_device_updatelogs_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6592343-8cf6-4a7b-b0f5-41eca5fbbb7e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
