# Generated by Django 4.2.6 on 2023-12-13 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('minions', '0006_alter_updatelogs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatelogs',
            name='update log',
        ),
        migrations.AddField(
            model_name='updatelogs',
            name='log_location',
            field=models.CharField(default='/home/user/logs'),
        ),
        migrations.AlterField(
            model_name='updatelogs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
